# Generated by Django 5.0.6 on 2024-06-13 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_invoice_options_alter_invoiceitem_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='slug',
            new_name='item_slug',
        ),
    ]
