# Generated by Django 5.0.6 on 2024-05-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_milestone_paymentmethod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contract', 'verbose_name_plural': 'Contracts'},
        ),
        migrations.AlterModelOptions(
            name='contracttemplate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contract Template', 'verbose_name_plural': 'Contract Templates'},
        ),
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['-created_at'], 'verbose_name': 'Milestone', 'verbose_name_plural': 'Milestones'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment Method', 'verbose_name_plural': 'Payment Methods'},
        ),
    ]
