# Generated by Django 5.0.6 on 2024-05-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='slug',
            field=models.SlugField(blank=True, max_length=400, null=True, unique=True),
        ),
    ]
