# Generated by Django 5.0.6 on 2024-05-29 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contract_slug'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_payment', to='payments.paymentmethod'),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
