# Generated by Django 5.0.6 on 2024-05-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_contract_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='slug',
            field=models.SlugField(blank=True, max_length=400, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='contracttemplate',
            name='slug',
            field=models.SlugField(blank=True, max_length=400, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='slug',
            field=models.SlugField(blank=True, max_length=400, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='slug',
            field=models.SlugField(blank=True, max_length=400, null=True, unique=True),
        ),
    ]
