# Generated by Django 5.0.6 on 2024-05-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_contract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='currency',
            field=models.CharField(default='KES', max_length=15),
            preserve_default=False,
        ),
    ]
