# Generated by Django 5.0.6 on 2024-06-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestonetasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonetask',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
