# Generated by Django 5.0.6 on 2024-06-06 08:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milestonetasks', '0002_milestonetask_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestonetask',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='task_file'),
        ),
    ]
