# Generated by Django 5.0.6 on 2024-06-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0005_alter_milestone_options_milestone_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('paid', 'Paid')], default='pending', max_length=50),
        ),
    ]
